Fix title and add s command

diff --git a/home/zshrc b/home/zshrc
--- a/home/zshrc
+++ b/home/zshrc
@@ -168,8 +168,8 @@ _within-bundled-project() {
 _run-with-bundler() {
   if _bundler-installed && _within-bundled-project; then
     if [ -f "./bin/bundle" ]; then
-      echo "$fg[blue]--> bin/bundle exec $@$reset_color" >&2
-      ./bin/bundle exec $@
+      echo "$fg[blue]--> bundle exec $@$reset_color" >&2
+      bundle exec $@
     else
       echo "$fg[blue]--> bundle exec $@$reset_color" >&2
       bundle exec $@
@@ -249,31 +249,38 @@ function fliptable {
  # }}}
 # Terminal Title {{{
 function title {
-  [ "$DISABLE_AUTO_TITLE" != "true" ] || return
+  if [[ "$DISABLE_AUTO_TITLE" == "true" ]] || [[ "$EMACS" == *term* ]]; then
+    return
+  fi
   if [[ "$TERM" == screen* ]]; then
     print -Pn "\ek$1:q\e\\" #set screen hardstatus, usually truncated at 20 chars
-  elif [[ "$TERM" == xterm* ]] || [[ $TERM == rxvt* ]] || [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
+  elif [[ "$TERM" == xterm* ]] || [[ $TERM == rxvt* ]] || [[ $TERM == ansi ]] || [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
     print -Pn "\e]2;$2:q\a" #set window name
     print -Pn "\e]1;$1:q\a" #set icon (=tab) name (will override window name on broken terminal)
   fi
 }
 
+ZSH_THEME_TERM_TAB_TITLE_IDLE="%15<..<%~%<<" #15 char left truncated PWD
+ZSH_THEME_TERM_TITLE_IDLE="%n@%m: %~"
+
 #Appears when you have the prompt
-function title_precmd {
-  title "%15<...<%~%<<" "%n@%m: %~"
+function termsupport_precmd {
+  title $ZSH_THEME_TERM_TAB_TITLE_IDLE $ZSH_THEME_TERM_TITLE_IDLE
 }
 
 #Appears at the beginning of (and during) of command execution
-function title_preexec {
+function termsupport_preexec {
   emulate -L zsh
   setopt extended_glob
-  local CMD=${1[(wr)^(*=*|sudo|ssh|-*)]} #cmd name only, or if this is sudo or ssh, the next cmd
-  title "$CMD" "%100>...>$2%<<"
+  local CMD=${1[(wr)^(*=*|sudo|ssh|rake|-*)]} #cmd name only, or if this is sudo or ssh, the next cmd
+  local LINE="${2:gs/$/\\$}"
+  LINE="${LINE:gs/%/%%}"
+  title "$CMD" "%100>...>$LINE%<<"
 }
 
 autoload -U add-zsh-hook
-add-zsh-hook precmd  title_precmd
-add-zsh-hook preexec title_preexec
+add-zsh-hook precmd  termsupport_precmd
+add-zsh-hook preexec termsupport_preexec
 # }}}
 # Custom Functions {{{
 # Kapow {{{
@@ -332,6 +339,18 @@ compctl -W ~/src -/ src
 
 rad(){cd ~/src/radius/$1;}
 compctl -W ~/src/radius -/ rad
+# }}}
+# s Command {{{
+s(){
+  cd ~
+  if cd "$(find src -type d -maxdepth 1 | ~/bin/selecta)" ; then
+    clear
+    echo "Changed to $(pwd)"
+  else
+    cd -
+    echo "Command failed"
+  fi
+}
 # }}}
 # }}}
 # Prompt {{{
